### ISSUE TITLE
Missing check arguments in cumBgGD function

### ISSUE THREAD

**Issue by NannaLojborg** [sashahafner/biogas#15]
In line 14 it says 'Check arguments', but there is nothing there. Check arguments should be added similar to how it is done in cumBg function.

**Comment by NannaLojborg** [comment]
Check arguments have been added. Though, new changes needs to be reviewed.

**Comment by sashahafner** [comment]
@NannaLojborg can you check line 60? It still seems to have a missing ). Maybe you didn't include this file in a commit. If you have committed and pushed all changes, I can fix it. Just trying to avoid a merge conflict.

**Comment by NannaLojborg** [comment]
I have added the missing bracket now. It was line 61 you noticed a missing bracket earlier and a 'c' in line 60. That is why I missed a bracket in line 60, after adding the 'c'.

**Comment by NannaLojborg** [comment]
All changes have been committed and pushed.

**Comment by sashahafner** [comment]
Great thanks!

**Comment by sashahafner** [comment]
Looks good. I made a few minor changes. We need to test it, and for that we should make a data set for testing.
