### ISSUE TITLE
cumBgVol() and cumBgMan() do not work without comp argument

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/biogas#25]
But they should

**Comment by sashahafner** [comment]
The vol function does work without the comp argument (i.e., with default of NULL) for longcombo format anyway. 

cpc <- cumBgVol(s3lcombo, 
             id.name = 'id', time.name = 'time.d',
             dat.name = 'vol.ml', comp.name = 'xCH4',
             extrap = TRUE)

It does not work with comp.name missing. I don't think it should. Did cumBg() work like this?

**Comment by sashahafner** [comment]
In fact, I think comp.name should always be required. So we should change this line to eliminate the NULL. 

  checkArgClassValue(comp.name, c('character', 'NULL'))

What do you think @NannaLojborg ?

**Comment by sashahafner** [comment]
Previous comment also applies to manometric function.

**Comment by sashahafner** [comment]
Maybe a very early version of the function could be used without comp, and there was some indication of this in the cumBg() help file.

**Comment by NannaLojborg** [comment]
cumBg() calculates biogas values even though composition arguments (both comp and comp.name) are not provided. The results comes with a warning about composition data not provided so CH4 results will not be returned. 

It seems to work for long structured data, but not wide and longcombo. cumBg() does not work on wide either, but returns biogas values and warning when having long and longcombo structure with no composition data provided (comp and comp.name)

**Comment by sashahafner** [comment]
Oh OK! So much for my memory. I'll look again at the new functions.

**Comment by sashahafner** [comment]
Fixed cumBgDataPrep() and cumBgVol() with commit 2aba1bb45b303b345e9b824ab284e969ff245be3

Added new internal have.comp variable to keep track. Now works for long, wide, and longcombo. Note that because comp.name has a default value, to call it up for longcombo with no composition data requires comp.name = NULL. 

cumBgMan() still needs to be updated.

**Comment by sashahafner** [comment]
CumBgMan() fixed with 3361c9b9618d4950e3ceeee4e053f40bb03819d2.
