### ISSUE TITLE
Bug in summBg() when show.rates=T and inoc.name not specified

### ISSUE THREAD

**Issue by jonasoh** [sashahafner/biogas#47]
While looking at the other summBg() problem with `show.rates = TRUE`, I observed an unexpected behavior with regard to rates when inoculum contribution is not subtracted. Starting from the previous example, on latest dev branch:
```
data(feedSetup)
data(feedVol)

cpw <- calcBgVol(feedVol, comp = 1, temp = 0, pres = 1, data.struct = "wide",
                       time.name = "time.d", vol.name = "1", dry = TRUE, interval = FALSE)

s1.noinoc <- summBg(cpw, feedSetup, id.name = 'id', time.name = 'time.d', descrip.name = 'descrip', norm.name = 'm.sub.vs', show.obs = TRUE, show.rates = TRUE)
```

The column rrvCH4 is now improperly sorted. Output from `plot(s1.noinoc[s1.noinoc$id==4,]$rrvCH4)`:
![bild](https://user-images.githubusercontent.com/6480370/144584668-f191b52c-56e5-4e8c-aa2a-73f5a43c313c.png)

Commenting out this line makes the data properly ordered again: https://github.com/sashahafner/biogas/blob/20b248839f9d50384fa398429dc0e0424172e851/R/summBg.R#L480

It seems to me that this line may be superfluous, as the dataframe is also sorted before returning (e.g., lines 501, 660, 694-704), but maybe I am missing an edge case here?

**Comment by jonasoh** [comment]
Ah, I realize now that the sorting is for the `diff()` to work of course. What about sorting the whole summ1 dataframe just before the for loop on L478?

**Comment by sashahafner** [comment]
> Ah, I realize now that the sorting is for the `diff()` to work of course. 

Yup. Added comment to code now.

> What about sorting the whole summ1 dataframe just before the for loop on L478?
Good suggestion. Earlier approach seems completely wrong, doesn't maintain order between `summ1` and `dd` subset. Probably the problem wasn't noticed earlier because this code typically sorts around line 427:

```
  if(!is.null(inoc.name)) {

    # Merge inoculum normalized volumes with sample data
    summ1 <- merge(summ1, inoc.vol, by = time.name)
```

Implemented your suggestion with a76aaff669ef60dbfdfbbb40bb691d50107d0b89

**Comment by sashahafner** [comment]
@jonasoh please close this issue if the solution seems OK. Also check new version of DESCRIPTION with added author: https://github.com/sashahafner/biogas/blob/dev/DESCRIPTION

**Comment by sashahafner** [comment]
Also let me know if you want to be added to this repo as a collaborator @jonasoh? Then you could make changes without a pull request. Up to you. It is OK if you prefer to just use pull requests or make suggestions in comments instead.

**Comment by jonasoh** [comment]
Looks good! 

Thank you for the recognition in DESCRIPTION. It suits me well to submit a PR or issue if/when I stumble upon something.
