### ISSUE TITLE
Automatic conversion of pres.std

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/biogas#5]
pres.std does not seem to automatically convert to new units in mass2vol() calls.

**Comment by sashahafner** [comment]
> library(biogas)
> options(unit.pres = 'mbar')
> mass2vol(0.001, 0.65, pres = 1500, temp = 32)
Using a standard pressure of 100 Pa and standard temperature of 273.15 K for
 standardizing volume.
[1] 557.4217
>

**Comment by NannaLojborg** [comment]
Issue has been fixed by adding minor changes to the code. Recommend to delete coding which are 'inactivated'.

**Comment by sashahafner** [comment]
Tested it and it works.
